apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-rag3-secret-5 
  janus-idp.io/tekton: test-rag3-secret-5
  backstage.io/kubernetes-id: test-rag3-secret-5
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: test-rag3-secret-5
resources: 
- application-dev.yaml