apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-rag3-secret-5
  janus-idp.io/tekton: test-rag3-secret-5
  backstage.io/kubernetes-id: test-rag3-secret-5
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: test-rag3-secret-5
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- deployment-database.yaml
- service-database.yaml
- database-config.yaml
- rhoai/
